//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideotekaClient.VideoReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zanr", Namespace="http://schemas.datacontract.org/2004/07/VideotekaService.DAL")]
    [System.SerializableAttribute()]
    public partial class Zanr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Film", Namespace="http://schemas.datacontract.org/2004/07/VideotekaService.DAL")]
    [System.SerializableAttribute()]
    public partial class Film : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilmZanrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string godinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFilmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zanrIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilmZanr {
            get {
                return this.FilmZanrField;
            }
            set {
                if ((object.ReferenceEquals(this.FilmZanrField, value) != true)) {
                    this.FilmZanrField = value;
                    this.RaisePropertyChanged("FilmZanr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string godina {
            get {
                return this.godinaField;
            }
            set {
                if ((object.ReferenceEquals(this.godinaField, value) != true)) {
                    this.godinaField = value;
                    this.RaisePropertyChanged("godina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFilm {
            get {
                return this.idFilmField;
            }
            set {
                if ((this.idFilmField.Equals(value) != true)) {
                    this.idFilmField = value;
                    this.RaisePropertyChanged("idFilm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                if ((object.ReferenceEquals(this.nazivField, value) != true)) {
                    this.nazivField = value;
                    this.RaisePropertyChanged("naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zanrId {
            get {
                return this.zanrIdField;
            }
            set {
                if ((this.zanrIdField.Equals(value) != true)) {
                    this.zanrIdField = value;
                    this.RaisePropertyChanged("zanrId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Klijent", Namespace="http://schemas.datacontract.org/2004/07/VideotekaService.DAL")]
    [System.SerializableAttribute()]
    public partial class Klijent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gradField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adresa {
            get {
                return this.adresaField;
            }
            set {
                if ((object.ReferenceEquals(this.adresaField, value) != true)) {
                    this.adresaField = value;
                    this.RaisePropertyChanged("adresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grad {
            get {
                return this.gradField;
            }
            set {
                if ((object.ReferenceEquals(this.gradField, value) != true)) {
                    this.gradField = value;
                    this.RaisePropertyChanged("grad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ime {
            get {
                return this.imeField;
            }
            set {
                if ((object.ReferenceEquals(this.imeField, value) != true)) {
                    this.imeField = value;
                    this.RaisePropertyChanged("ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prezime {
            get {
                return this.prezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.prezimeField, value) != true)) {
                    this.prezimeField = value;
                    this.RaisePropertyChanged("prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Posudba", Namespace="http://schemas.datacontract.org/2004/07/VideotekaService.DAL")]
    [System.SerializableAttribute()]
    public partial class Posudba : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedijField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivFilmaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime datumPosudbeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> datumPovrataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idFilmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idKorisnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipmedijaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prezimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Medij {
            get {
                return this.MedijField;
            }
            set {
                if ((object.ReferenceEquals(this.MedijField, value) != true)) {
                    this.MedijField = value;
                    this.RaisePropertyChanged("Medij");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivFilma {
            get {
                return this.NazivFilmaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivFilmaField, value) != true)) {
                    this.NazivFilmaField = value;
                    this.RaisePropertyChanged("NazivFilma");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime datumPosudbe {
            get {
                return this.datumPosudbeField;
            }
            set {
                if ((this.datumPosudbeField.Equals(value) != true)) {
                    this.datumPosudbeField = value;
                    this.RaisePropertyChanged("datumPosudbe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> datumPovrata {
            get {
                return this.datumPovrataField;
            }
            set {
                if ((this.datumPovrataField.Equals(value) != true)) {
                    this.datumPovrataField = value;
                    this.RaisePropertyChanged("datumPovrata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFilm {
            get {
                return this.idFilmField;
            }
            set {
                if ((this.idFilmField.Equals(value) != true)) {
                    this.idFilmField = value;
                    this.RaisePropertyChanged("idFilm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idKorisnik {
            get {
                return this.idKorisnikField;
            }
            set {
                if ((this.idKorisnikField.Equals(value) != true)) {
                    this.idKorisnikField = value;
                    this.RaisePropertyChanged("idKorisnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipmedija {
            get {
                return this.idTipmedijaField;
            }
            set {
                if ((this.idTipmedijaField.Equals(value) != true)) {
                    this.idTipmedijaField = value;
                    this.RaisePropertyChanged("idTipmedija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ime {
            get {
                return this.imeField;
            }
            set {
                if ((object.ReferenceEquals(this.imeField, value) != true)) {
                    this.imeField = value;
                    this.RaisePropertyChanged("ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prezime {
            get {
                return this.prezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.prezimeField, value) != true)) {
                    this.prezimeField = value;
                    this.RaisePropertyChanged("prezime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipMedija", Namespace="http://schemas.datacontract.org/2004/07/VideotekaService.DAL")]
    [System.SerializableAttribute()]
    public partial class TipMedija : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string naziv {
            get {
                return this.nazivField;
            }
            set {
                if ((object.ReferenceEquals(this.nazivField, value) != true)) {
                    this.nazivField = value;
                    this.RaisePropertyChanged("naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VideoReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetZanr", ReplyAction="http://tempuri.org/IService1/GetZanrResponse")]
        VideotekaClient.VideoReference.Zanr[] GetZanr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetZanr", ReplyAction="http://tempuri.org/IService1/GetZanrResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.Zanr[]> GetZanrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUppZanr", ReplyAction="http://tempuri.org/IService1/AddUppZanrResponse")]
        void AddUppZanr(VideotekaClient.VideoReference.Zanr zanr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUppZanr", ReplyAction="http://tempuri.org/IService1/AddUppZanrResponse")]
        System.Threading.Tasks.Task AddUppZanrAsync(VideotekaClient.VideoReference.Zanr zanr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteZanr", ReplyAction="http://tempuri.org/IService1/deleteZanrResponse")]
        void deleteZanr(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteZanr", ReplyAction="http://tempuri.org/IService1/deleteZanrResponse")]
        System.Threading.Tasks.Task deleteZanrAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteZanrSafe", ReplyAction="http://tempuri.org/IService1/DeleteZanrSafeResponse")]
        int DeleteZanrSafe(int idZanr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteZanrSafe", ReplyAction="http://tempuri.org/IService1/DeleteZanrSafeResponse")]
        System.Threading.Tasks.Task<int> DeleteZanrSafeAsync(int idZanr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilmZanr", ReplyAction="http://tempuri.org/IService1/GetFilmZanrResponse")]
        VideotekaClient.VideoReference.Film[] GetFilmZanr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilmZanr", ReplyAction="http://tempuri.org/IService1/GetFilmZanrResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> GetFilmZanrAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilm", ReplyAction="http://tempuri.org/IService1/GetFilmResponse")]
        VideotekaClient.VideoReference.Film[] GetFilm();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilm", ReplyAction="http://tempuri.org/IService1/GetFilmResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> GetFilmAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchFilm", ReplyAction="http://tempuri.org/IService1/SearchFilmResponse")]
        VideotekaClient.VideoReference.Film[] SearchFilm(string naziv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchFilm", ReplyAction="http://tempuri.org/IService1/SearchFilmResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> SearchFilmAsync(string naziv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSlobodniFilmovi", ReplyAction="http://tempuri.org/IService1/GetSlobodniFilmoviResponse")]
        VideotekaClient.VideoReference.Film[] GetSlobodniFilmovi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSlobodniFilmovi", ReplyAction="http://tempuri.org/IService1/GetSlobodniFilmoviResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> GetSlobodniFilmoviAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilmDDL", ReplyAction="http://tempuri.org/IService1/GetFilmDDLResponse")]
        VideotekaClient.VideoReference.Film[] GetFilmDDL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFilmDDL", ReplyAction="http://tempuri.org/IService1/GetFilmDDLResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> GetFilmDDLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUppFilm", ReplyAction="http://tempuri.org/IService1/AddUppFilmResponse")]
        void AddUppFilm(VideotekaClient.VideoReference.Film film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUppFilm", ReplyAction="http://tempuri.org/IService1/AddUppFilmResponse")]
        System.Threading.Tasks.Task AddUppFilmAsync(VideotekaClient.VideoReference.Film film);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFilm", ReplyAction="http://tempuri.org/IService1/DeleteFilmResponse")]
        void DeleteFilm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFilm", ReplyAction="http://tempuri.org/IService1/DeleteFilmResponse")]
        System.Threading.Tasks.Task DeleteFilmAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFilmSafe", ReplyAction="http://tempuri.org/IService1/DeleteFilmSafeResponse")]
        int DeleteFilmSafe(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteFilmSafe", ReplyAction="http://tempuri.org/IService1/DeleteFilmSafeResponse")]
        System.Threading.Tasks.Task<int> DeleteFilmSafeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKlijent", ReplyAction="http://tempuri.org/IService1/GetKlijentResponse")]
        VideotekaClient.VideoReference.Klijent[] GetKlijent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKlijent", ReplyAction="http://tempuri.org/IService1/GetKlijentResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.Klijent[]> GetKlijentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUppKlijent", ReplyAction="http://tempuri.org/IService1/AddUppKlijentResponse")]
        void AddUppKlijent(VideotekaClient.VideoReference.Klijent klijent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUppKlijent", ReplyAction="http://tempuri.org/IService1/AddUppKlijentResponse")]
        System.Threading.Tasks.Task AddUppKlijentAsync(VideotekaClient.VideoReference.Klijent klijent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteKlijent", ReplyAction="http://tempuri.org/IService1/DeleteKlijentResponse")]
        void DeleteKlijent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteKlijent", ReplyAction="http://tempuri.org/IService1/DeleteKlijentResponse")]
        System.Threading.Tasks.Task DeleteKlijentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteKlijentSafe", ReplyAction="http://tempuri.org/IService1/DeleteKlijentSafeResponse")]
        int DeleteKlijentSafe(int idKlijent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteKlijentSafe", ReplyAction="http://tempuri.org/IService1/DeleteKlijentSafeResponse")]
        System.Threading.Tasks.Task<int> DeleteKlijentSafeAsync(int idKlijent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKlijentDDL", ReplyAction="http://tempuri.org/IService1/GetKlijentDDLResponse")]
        VideotekaClient.VideoReference.Klijent[] GetKlijentDDL();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetKlijentDDL", ReplyAction="http://tempuri.org/IService1/GetKlijentDDLResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.Klijent[]> GetKlijentDDLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAktivnaPosudba", ReplyAction="http://tempuri.org/IService1/GetAktivnaPosudbaResponse")]
        VideotekaClient.VideoReference.Posudba[] GetAktivnaPosudba();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAktivnaPosudba", ReplyAction="http://tempuri.org/IService1/GetAktivnaPosudbaResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.Posudba[]> GetAktivnaPosudbaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUppPosudba", ReplyAction="http://tempuri.org/IService1/AddUppPosudbaResponse")]
        void AddUppPosudba(VideotekaClient.VideoReference.Posudba posudba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUppPosudba", ReplyAction="http://tempuri.org/IService1/AddUppPosudbaResponse")]
        System.Threading.Tasks.Task AddUppPosudbaAsync(VideotekaClient.VideoReference.Posudba posudba);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePosudba", ReplyAction="http://tempuri.org/IService1/DeletePosudbaResponse")]
        void DeletePosudba(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeletePosudba", ReplyAction="http://tempuri.org/IService1/DeletePosudbaResponse")]
        System.Threading.Tasks.Task DeletePosudbaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTipMedija", ReplyAction="http://tempuri.org/IService1/GetTipMedijaResponse")]
        VideotekaClient.VideoReference.TipMedija[] GetTipMedija();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTipMedija", ReplyAction="http://tempuri.org/IService1/GetTipMedijaResponse")]
        System.Threading.Tasks.Task<VideotekaClient.VideoReference.TipMedija[]> GetTipMedijaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : VideotekaClient.VideoReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<VideotekaClient.VideoReference.IService1>, VideotekaClient.VideoReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VideotekaClient.VideoReference.Zanr[] GetZanr() {
            return base.Channel.GetZanr();
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.Zanr[]> GetZanrAsync() {
            return base.Channel.GetZanrAsync();
        }
        
        public void AddUppZanr(VideotekaClient.VideoReference.Zanr zanr) {
            base.Channel.AddUppZanr(zanr);
        }
        
        public System.Threading.Tasks.Task AddUppZanrAsync(VideotekaClient.VideoReference.Zanr zanr) {
            return base.Channel.AddUppZanrAsync(zanr);
        }
        
        public void deleteZanr(int id) {
            base.Channel.deleteZanr(id);
        }
        
        public System.Threading.Tasks.Task deleteZanrAsync(int id) {
            return base.Channel.deleteZanrAsync(id);
        }
        
        public int DeleteZanrSafe(int idZanr) {
            return base.Channel.DeleteZanrSafe(idZanr);
        }
        
        public System.Threading.Tasks.Task<int> DeleteZanrSafeAsync(int idZanr) {
            return base.Channel.DeleteZanrSafeAsync(idZanr);
        }
        
        public VideotekaClient.VideoReference.Film[] GetFilmZanr() {
            return base.Channel.GetFilmZanr();
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> GetFilmZanrAsync() {
            return base.Channel.GetFilmZanrAsync();
        }
        
        public VideotekaClient.VideoReference.Film[] GetFilm() {
            return base.Channel.GetFilm();
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> GetFilmAsync() {
            return base.Channel.GetFilmAsync();
        }
        
        public VideotekaClient.VideoReference.Film[] SearchFilm(string naziv) {
            return base.Channel.SearchFilm(naziv);
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> SearchFilmAsync(string naziv) {
            return base.Channel.SearchFilmAsync(naziv);
        }
        
        public VideotekaClient.VideoReference.Film[] GetSlobodniFilmovi() {
            return base.Channel.GetSlobodniFilmovi();
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> GetSlobodniFilmoviAsync() {
            return base.Channel.GetSlobodniFilmoviAsync();
        }
        
        public VideotekaClient.VideoReference.Film[] GetFilmDDL() {
            return base.Channel.GetFilmDDL();
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.Film[]> GetFilmDDLAsync() {
            return base.Channel.GetFilmDDLAsync();
        }
        
        public void AddUppFilm(VideotekaClient.VideoReference.Film film) {
            base.Channel.AddUppFilm(film);
        }
        
        public System.Threading.Tasks.Task AddUppFilmAsync(VideotekaClient.VideoReference.Film film) {
            return base.Channel.AddUppFilmAsync(film);
        }
        
        public void DeleteFilm(int id) {
            base.Channel.DeleteFilm(id);
        }
        
        public System.Threading.Tasks.Task DeleteFilmAsync(int id) {
            return base.Channel.DeleteFilmAsync(id);
        }
        
        public int DeleteFilmSafe(int id) {
            return base.Channel.DeleteFilmSafe(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteFilmSafeAsync(int id) {
            return base.Channel.DeleteFilmSafeAsync(id);
        }
        
        public VideotekaClient.VideoReference.Klijent[] GetKlijent() {
            return base.Channel.GetKlijent();
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.Klijent[]> GetKlijentAsync() {
            return base.Channel.GetKlijentAsync();
        }
        
        public void AddUppKlijent(VideotekaClient.VideoReference.Klijent klijent) {
            base.Channel.AddUppKlijent(klijent);
        }
        
        public System.Threading.Tasks.Task AddUppKlijentAsync(VideotekaClient.VideoReference.Klijent klijent) {
            return base.Channel.AddUppKlijentAsync(klijent);
        }
        
        public void DeleteKlijent(int id) {
            base.Channel.DeleteKlijent(id);
        }
        
        public System.Threading.Tasks.Task DeleteKlijentAsync(int id) {
            return base.Channel.DeleteKlijentAsync(id);
        }
        
        public int DeleteKlijentSafe(int idKlijent) {
            return base.Channel.DeleteKlijentSafe(idKlijent);
        }
        
        public System.Threading.Tasks.Task<int> DeleteKlijentSafeAsync(int idKlijent) {
            return base.Channel.DeleteKlijentSafeAsync(idKlijent);
        }
        
        public VideotekaClient.VideoReference.Klijent[] GetKlijentDDL() {
            return base.Channel.GetKlijentDDL();
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.Klijent[]> GetKlijentDDLAsync() {
            return base.Channel.GetKlijentDDLAsync();
        }
        
        public VideotekaClient.VideoReference.Posudba[] GetAktivnaPosudba() {
            return base.Channel.GetAktivnaPosudba();
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.Posudba[]> GetAktivnaPosudbaAsync() {
            return base.Channel.GetAktivnaPosudbaAsync();
        }
        
        public void AddUppPosudba(VideotekaClient.VideoReference.Posudba posudba) {
            base.Channel.AddUppPosudba(posudba);
        }
        
        public System.Threading.Tasks.Task AddUppPosudbaAsync(VideotekaClient.VideoReference.Posudba posudba) {
            return base.Channel.AddUppPosudbaAsync(posudba);
        }
        
        public void DeletePosudba(int id) {
            base.Channel.DeletePosudba(id);
        }
        
        public System.Threading.Tasks.Task DeletePosudbaAsync(int id) {
            return base.Channel.DeletePosudbaAsync(id);
        }
        
        public VideotekaClient.VideoReference.TipMedija[] GetTipMedija() {
            return base.Channel.GetTipMedija();
        }
        
        public System.Threading.Tasks.Task<VideotekaClient.VideoReference.TipMedija[]> GetTipMedijaAsync() {
            return base.Channel.GetTipMedijaAsync();
        }
    }
}
